name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main  # デプロイ対象のブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # コードをGitHubリポジトリから取得
    - name: Checkout code
      uses: actions/checkout@v3

    # Python環境をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.9'  # 使用しているPythonのバージョン

    # 必要なパッケージをインストール
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt  # 必要なパッケージをインストール

    # Azure App Service へのデプロイ
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "tech0-gen-9-step3-1-py-68"  # Azureのバックエンド用App Service名
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
